version: "3.8" #Specifies the version of the Docker Compose file format being used. In this case, it’s version 3.8, which provides certain features and compatibility for Docker Compose.
services: # Defines the list of services (in this case, containers) that Docker Compose will manage. Each service represents a different part of your application.
  backend_sample: #The name of the service.
    container_name: backend_sample_container #Specifies the name of the container that will be created when the service runs. In this case, it will be named backend_sample_container.
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3000:3000
    env_file: ./src/configs/.env.development
    environment:
      - DOCKER_ENV=true
    volumes:
      - ./src:/app/src # HOT RELOADING, ANY CHANGE IN SRC FOLDER OUR APP WILL RESTART
